{
  "default": {
    "adapter": "postgresql",
    "pool": "<%= ENV.fetch(\"RAILS_MAX_THREADS\") { 5 } %>",
    "encoding": "unicode"
  },
  "development": {
    "adapter": "postgresql",
    "encoding": "unicode",
    "pool": "<%= ENV.fetch(\"RAILS_MAX_THREADS\") { 5 } %>",
    "database": "myapp_development"
  },
  "test": {
    "adapter": "postgresql",
    "encoding": "unicode",
    "pool": "<%= ENV.fetch(\"RAILS_MAX_THREADS\") { 5 } %>",
    "database": "myapp_test"
  },
  "production": {
    "username": "myapp",
    "password": "<%= ENV['MYAPP_DATABASE_PASSWORD'] %>",
    "database": "myapp_production",
    "adapter": "postgresql",
    "encoding": "unicode",
    "pool": "<%= ENV.fetch(\"RAILS_MAX_THREADS\") { 5 } %>"
  }
}
